=== almlys/sevendeset/docs/spec/BootStrap.dtd
<!--

    sd7 Project BootStrap Document Type Definition
    Copyright (C) 2008 Alberto MontaÃ±ola Lacort
    Licensed under the GNU GPL. For full terms see the file COPYING.

    Id: $Id$

-->

<!ELEMENT bootstrap (module)+>
<!ATTLIST bootstrap
	default_target #REQUIRED>

<!ELEMENT module (comment?,license?,source+,patch?,build?,install?)>
<!ATTLIST module
	name ID #REQUIRED
	ignore CDATA #IMPLIED
	depends CDATA #IMPLIED>

<!ELEMENT comment (#PCDATA)>
<!ELEMENT license (#PCDATA)>

<!ELEMENT source EMPTY>
<!ATTLIST source
	addr CDATA #REQUIRED
	method CDATA #REQUIRED
	renamefrom CDATA #IMPLIED
	md5 CDATA #IMPLIED
	module CDATA #IMPLIED
	platform CDATA #IMPLIED
	arch CDATA #IMPLIED>

<!ELEMENT patch EMPTY>
<!ATTLIST patch
	addr CDATA #REQUIRED>

<!ELEMENT build (cmd)+>

<!ELEMENT install (cmd)+>

<!ELEMENT cmd (#PCDATA)>
<!ATTLIST cmd
	cmd CDATA #IMPLIED
	path CDATA #IMPLIED>

=== almlys/sevendeset/config/bootstrap.xml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE bootstrap SYSTEM "http://7d7.almlys.org/spec/draft/BootStrap.dtd">
<bootstrap default_target='sd7'>

	<module name='cg' ignore='no'>
		<comment>
			Unfortunately the next library is not Open Source
			This is the 32 bits version of the library
			Check: http://developer.nvidia.com/object/cg_toolkit.html for more info
			Note: Ogre can be compiled without the cg library, but well, you now how things will look without it.
		</comment>
		<license>Propietary</license>
		<source addr='http://7d7.almlys.org/downloads/depends/cg/Cg-2.0_Jan2008_x86.tar.gz'
						method='wget' renamefrom='usr'
						md5='c26a8fd98a4ed8b9a2e418a04554d41a'
						platform='linux' arch='i686' />
		<source addr='http://developer.download.nvidia.com/cg/Cg_2.0/2.0.0012/Cg-2.0_Jan2008_x86.tar.gz'
						method='wget' renamefrom='usr'
						md5='c26a8fd98a4ed8b9a2e418a04554d41a'
						platform='linux' arch='i686' />
		<source addr='http://7d7.almlys.org/downloads/depends/cg/Cg-2.0_Jan2008_x86_64.tar.gz'
						method='wget' renamefrom='usr'
						md5='41d0c09e09e191c1847620a13696cce7'
						platform='linux' arch='x86_64' />
		<source addr='http://developer.download.nvidia.com/cg/Cg_2.0/2.0.0012/Cg-2.0_Jan2008_x86_64.tar.gz'
						method='wget' renamefrom='usr'
						md5='41d0c09e09e191c1847620a13696cce7'
						platform='linux' arch='x86_64' />
		<install>
			<cmd>cp -rvp * $PREFIX</cmd>
		</install>
	</module>
	
	<module name='ilmbase' ignore='no'>
		<comment>
			Base library for openEXR
		</comment>
		<license>BSD</license>
		<source addr='http://7d7.almlys.org/downloads/depends/openexr/ilmbase-1.0.1.tar.gz'
						method='wget' renamefrom='ilmbase-1.0.1'
						md5='f76f094e69a6079b0beb93d97e2a217e'/>
		<source addr='http://download.savannah.nongnu.org/releases/openexr/ilmbase-1.0.1.tar.gz'
						method='wget' renamefrom='ilmbase-1.0.1'
						md5='f76f094e69a6079b0beb93d97e2a217e'/>
		<build>
			<cmd>./configure --prefix=$PREFIX</cmd>
			<cmd>make -j 2</cmd>
		</build>
		<install>
			<cmd>make install</cmd>
		</install>
	</module>
	
	<module name='openexr' ignore='no' depends='ilmbase'>
		<comment>
			Optional Library for OpenEXR HDR image file format
		</comment>
		<license>BSD</license>
		<source addr='http://7d7.almlys.org/downloads/depends/openexr/openexr-1.6.1.tar.gz'
						method='wget' renamefrom='openexr-1.6.1'
						md5='11951f164f9c872b183df75e66de145a'/>
		<source addr='http://download.savannah.nongnu.org/releases/openexr/openexr-1.6.1.tar.gz'
						method='wget' renamefrom='openexr-1.6.1'
						md5='11951f164f9c872b183df75e66de145a'/>
		<build>
			<cmd>./configure --prefix=$PREFIX</cmd>
			<cmd>make -j 2</cmd>
		</build>
		<install>
			<cmd>make install</cmd>
		</install>
	</module>

	<module name='freeimage' ignore='no' >
		<comment>
			Graphics support library
		</comment>
		<license>(dual) GPLv2 or later / FreeImage Public License</license>
		<source addr='http://7d7.almlys.org/downloads/depends/freeimage/FreeImage3100.zip'
						method='wget' renamefrom='FreeImage'
						md5='2e57135e26bb487cc8e13ee7b7e0a595' />
		<source addr='http://downloads.sourceforge.net/freeimage/FreeImage3100.zip'
						method='wget' renamefrom='FreeImage'
						md5='2e57135e26bb487cc8e13ee7b7e0a595' />
		<!-- Please use subversion version of Freeimage for 64 bits -->
		<build>
			<!-- Dirty patch grabben from python-ogre distribution -->
			<cmd>sed --in-place -s 's|/usr/include|\$(DESTINC)|' Makefile.*</cmd>
			<cmd>sed --in-place -s 's|/usr/lib|\$(DESTLIB)|' Makefile.*</cmd>
			<cmd>sed --in-place -s 's|-o root -g root||' Makefile.*</cmd>
			<cmd>sed --in-place -s 's|ldconfig||' Makefile.*</cmd>
			<!-- End dirty patch -->
			<cmd>make</cmd>
		</build>
		<install>
			<cmd>make DESTINC=$PREFIX/include DESTLIB=$PREFIX/lib install</cmd>
		</install>
	</module>

	<module name='pcre' ignore='no' >
		<comment>
			Regular expression library
			(Not installed on the UdL Fedora's, or it's not the correct version)
		</comment>
		<license>BSD</license>
		<source addr='http://7d7.almlys.org/downloads/depends/pcre/pcre-7.6.tar.bz2'
						method='wget' renamefrom='pcre-7.6'
						md5='2af38e083fb90ef60fa9eda7cc290e86' />
		<source addr='http://downloads.sourceforge.net/pcre/pcre-7.6.tar.bz2'
						method='wget' renamefrom='pcre-7.6'
						md5='2af38e083fb90ef60fa9eda7cc290e86' />
		<build>
			<cmd>./configure --prefix=$PREFIX --enable-unicode-properties</cmd>
			<cmd>make -j 2</cmd>
		</build>
		<install>
			<cmd>make install</cmd>
		</install>
	</module>

	<module name='zziplib' ignore='no' >
		<comment>
			Library for opening zip files
		</comment>
		<license>LGPL/MPL</license>
		<source addr='http://7d7.almlys.org/downloads/depends/zziplib/zziplib-0.13.49.tar.bz2'
						method='wget' renamefrom='zziplib-0.13.49'
						md5='5f7b88ebb2bcd7e8044328482d079661' />
		<source addr='http://downloads.sourceforge.net/zziplib/zziplib-0.13.49.tar.bz2'
						method='wget' renamefrom='zziplib-0.13.49'
						md5='5f7b88ebb2bcd7e8044328482d079661' />
		<build>
			<cmd>./configure --prefix=$PREFIX --datadir=$PREFIX/share</cmd>
			<cmd>make -j 2</cmd>
		</build>
		<install>
			<cmd>make install</cmd>
		</install>
	</module>


	<module name='ois' ignore='no' depends='freeimage' >
		<comment>
			Object Oriented Input System
		</comment>
		<license>zlib/libpng</license>
		<!--
		<source addr='http://7d7.almlys.org/downloads/depends/ois/ois-1.0RC1.tar.gz'
						method='wget' renamefrom='ois-1.0RC1'
						md5='05cbd131fb0477e1cbd4b115ccef2c90'/>
		<source addr='http://prdownloads.sourceforge.net/wgois/ois-1.0RC1.tar.gz'
						method='wget' renamefrom='ois-1.0RC1'
						md5='05cbd131fb0477e1cbd4b115ccef2c90'/>
		<patch addr='ois.patch' />
		-->
		<source addr='http://7d7.almlys.org/downloads/depends/ois/ois_1.2.0.tar.gz'
						method='wget'
						md5='6a8cedad04f095127ca1455162fec955'/>
		<source addr='http://downloads.sourceforge.net/wgois/ois_1.2.0.tar.gz'
						method='wget'
						md5='6a8cedad04f095127ca1455162fec955'/>
		<build>
			<cmd>./bootstrap</cmd>
			<cmd>./configure --prefix=$PREFIX</cmd>
			<cmd>make -j 2</cmd>
		</build>
		<install>
			<cmd>make install</cmd>
		</install>
	</module>

	<module name='cegui' ignore='no'>
		<comment>
			GUI
		</comment>
		<license>MIT</license>
		<source addr='http://7d7.almlys.org/downloads/depends/cegui/CEGUI-0.5.0b.tar.gz'
						method='wget' renamefrom='CEGUI-0.5.0'
						md5='b42322a33c6a06eede76b15f75694a17'/>
		<source addr='http://prdownloads.sourceforge.net/crayzedsgui/CEGUI-0.5.0b.tar.gz'
						method='wget' renamefrom='CEGUI-0.5.0'
						md5='b42322a33c6a06eede76b15f75694a17'/>

		<!-- <source addr='http://7d7.almlys.org/downloads/depends/cegui/CEGUI-0.6.0.tar.gz'
						method='wget' renamefrom='CEGUI-0.6.0'
						md5='a7772b20a4e3530298e3e28c4eaec1bb'/>
		<source addr='http://prdownloads.sourceforge.net/crayzedsgui/CEGUI-0.6.0.tar.gz'
						method='wget' renamefrom='CEGUI-0.6.0'
						md5='a7772b20a4e3530298e3e28c4eaec1bb'/> -->


		<build>
			<cmd>./configure --prefix=$PREFIX --without-ogre-renderer --with-default-image-codec=FreeImageImageCodec --with-default-xml-parser=ExpatParser --enable-freeimage --enable-samples --disable-tinyxml --enable-expat </cmd>
			<cmd>make -j 2</cmd>
		</build>
		<install>
			<cmd>make install</cmd>
		</install>
	</module>
	
	
	<module name='ogre' ignore='no' depends='cg,openexr,cegui,ois,boost'>
		<comment>
			The mother of the world
		</comment>
		<license>(dual) LGPLv2.1 or later / unrestricted(comercial)</license>
		<source addr='http://7d7.almlys.org/downloads/depends/ogre/ogre-linux_osx-v1-4-7.tar.bz2'
						method='wget' renamefrom='ogrenew'
						md5='f44cba3f7362f6d8ca4187dee0d588ef' />
		<source addr='http://prdownloads.sourceforge.net/ogre/ogre-linux_osx-v1-4-7.tar.bz2'
						method='wget' renamefrom='ogrenew'
						md5='f44cba3f7362f6d8ca4187dee0d588ef' />
		<!-- Some patches should be added here!! -->
		<build>
			<!--<cmd>./configure - - prefix=$PREFIX - - enable-openexr - - enable-threading</cmd>-->
			<cmd>./configure --prefix=$PREFIX --enable-openexr --with-gui=Xt --disable-devil --enable-freeimage</cmd>
			<cmd>make -j 2</cmd>
		</build>
		<install>
			<cmd>make install</cmd>
		</install>
	</module>

	<module name='gccxml' ignore='no'>
		<comment>
			C++ to xml generator
			Latest stable version is too old, soo we need to get latest **unstable** from cvs (cross fingers)
		</comment>
		<license>GPLv2 or later</license>
		<!-- <source addr='http://7d7.almlys.org/downloads/depends/gccxml/gccxml20080320.tar.bz2'
						method='wget' renamefrom='gccxml'
						md5='13fa36e86ebd7cd7470ce977b6076fdf'
						branch='stable' /> -->
		<source addr='http://7d7.almlys.org/downloads/depends/gccxml/gccxml20080504.tar.bz2'
						method='wget' renamefrom='gccxml'
						md5='25461b1563a3dda9350c134318d23352'
						branch='stable' />

		<source addr=':pserver:anoncvs@www.gccxml.org:/cvsroot/GCC_XML'
						method='cvs' module='gccxml' revision='20080504'
						branch='stable' />
		<source addr=':pserver:anoncvs@www.gccxml.org:/cvsroot/GCC_XML'
						method='cvs' module='gccxml'
						branch='devel' />
		<build>
			<cmd cmd='mkdir' path='gccxml-build' />
			<cmd cmd='cd' path='gccxml-build' />
			<cmd>cmake ../ -DCMAKE_INSTALL_PREFIX:PATH=$PREFIX</cmd>
			<cmd>make</cmd>
		</build>
		<install>
			<cmd cmd='cd' path='gccxml-build' />
			<cmd>make install</cmd>
		</install>
	</module>
	
	<module name='pygccxml' ignore='no' depends='gccxml'>
		<comment>
			py++
			Code generator for Boost.Python
		</comment>
		<license>Boost</license>
		<!-- <source addr='http://7d7.almlys.org/downloads/depends/pygccxml/pygccxml20080320.tar.bz2'
						method='wget' renamefrom='pygccxml'
						md5='97e8dfc0ceb72412fb63f683e66c4c21'
						branch='stable' /> -->
		<source addr='http://7d7.almlys.org/downloads/depends/pygccxml/pygccxml20080504.tar.bz2'
						method='wget' renamefrom='pygccxml'
						md5='a43c3ffdeb862262341085f45306da7b'
						branch='stable' />
