=== almlys/sevendeset/docs/spec/sd7Config.dtd
<!--

    sd7 Project Configuration Document Type Definition
    Copyright (C) 2008 Alberto MontaÃ±ola Lacort
    Licensed under the GNU GPL. For full terms see the file COPYING.

    Id: $Id$

-->

<!ELEMENT sd7config (section)+>

<!ELEMENT section (option)*>
<!ATTLIST section
	name CDATA #REQUIRED>

<!ELEMENT option EMPTY>
<!ATTLIST option
	name CDATA #REQUIRED
	value CDATA #REQUIRED>

=== almlys/sevendeset/config/config.xml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE sd7config SYSTEM "http://7d7.almlys.org/spec/draft/sd7Config.dtd">
<sd7config>

	<section name='global'>
		<option name='BootStrap.downloadPath' value='downloads' />
		<option name='BootStrap.outputPath' value='depends' />
		<option name='BootStrap.prefix' value='runtime' />
		<option name='BootStrap.patches' value='patches' />
		<option name='BootStrap.manifest' value='config/bootstrap.xml' />
		<option name='Engine.OgreRenderer.PluginsPath' value='runtime/lib/OGRE' />
		<option name='Engine.OgreRenderer.direct3d' value='false' />
	</section>
	
	<section name='engine.OgreRenderer.plugins'>
		<option name='RenderSystem_Direct3D9' value='disabled' />
		<option name='RenderSystem_GL' value='enabled' />
		<option name='Plugin_ParticleFX' value='enabled' />
		<option name='Plugin_BSPSceneManager' value='enabled' />
		<option name='Plugin_OctreeSceneManager' value='enabled' />
		<option name='Plugin_CgProgramManager' value='enabled' />
		<option name='Plugin_EXRCodec' value='enabled' />
	</section>

</sd7config>
