=== almlys/sevendeset/docs/spec/sd7Hooks.dtd
<!--

    sd7 Project Configuration Document Type Definition
    Copyright (C) 2008 Alberto MontaÃ±ola Lacort
    Licensed under the GNU GPL. For full terms see the file COPYING.

    Id: $Id$

-->

<!ELEMENT sd7hooks (controller)+>

<!ELEMENT controller (param)*>
<!ATTLIST controller
	name CDATA #REQUIRED
    bind CDATA #REQUIRED
    autostart CDATA #IMPLIED>

<!ELEMENT param (#PCDATA)>
<!ATTLIST param
	name CDATA #REQUIRED>

=== almlys/sevendeset/config/hooks.xml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE sd7hooks SYSTEM "http://7d7.almlys.org/spec/draft/sd7Hooks.dtd">
<sd7hooks>

	<!-- Define Basic System Key bindings -->
	<controller name='basicInput'
    bind='sd7.system.basicInput.MyBasicInputHandler'
    autostart='true' />

    <!-- Stats window -->
    <controller name = 'Stats'
    bind = 'sd7.system.stats.Stats'
    autostart = 'true' >
        <param name = 'visible'>true</param>
    </controller>

	<!-- Loads the layout defined in the parameter	-->
	<controller name='gui' bind='sd7.logic.gui.GUI' autostart='false' >
		<param name='layout'>stats.layout</param>
	</controller>
	
    <!-- Script that set ups the Camera -->
    <controller name = 'Cam'
    bind = 'sd7.logic.camera.Camera'
    autostart = 'true' />

	<controller name='startup' bind='sd7.system.startup.StartupHandler' />
	
	<controller name='chatapp' bind='sd7.logic.chatapp.ChatApp' autostart='true' />

	
</sd7hooks>
