=== almlys/sevendeset/docs/spec/sd7Input.dtd
<!--

    sd7 Project Configuration Document Type Definition
    Copyright (C) 2008 Alberto MontaÃ±ola Lacort
    Licensed under the GNU GPL. For full terms see the file COPYING.

    Id: $Id$

-->

<!ELEMENT sd7input (input)+>

<!-- target: Name of a destination instance that will recieve the event -->
<!-- priority: Input priority
        prio: 0 - Goes to the PriorityEvents list of the ActionMapper
                    it will be not processed by the GUI if the HookMGR
                    processes it.
        prio: 1 - Goes to the normal Events list of the ActionMapper -->

<!ELEMENT input (action?,axis?)*>
<!ATTLIST input
	device CDATA #REQUIRED
    target CDATA #IMPLIED
    priority CDATA #IMPLIED>

<!ELEMENT action EMPTY>
<!ATTLIST action
	name CDATA #REQUIRED
	key CDATA #IMPLIED
    mask CDATA #IMPLIED
    target CDATA #IMPLIED
    button CDATA #IMPLIED
    priority CDATA #IMPLIED>

<!ELEMENT axis EMPTY>
<!ATTLIST axis
    name CDATA #REQUIRED
    id CDATA #REQUIRED
    target CDATA #IMPLIED
    priority CDATA #IMPLIED
    invert CDATA #IMPLIED>

=== almlys/sevendeset/config/input.xml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE sd7input SYSTEM "http://7d7.almlys.org/spec/draft/sd7Input.dtd">
<sd7input>

	<input device='keyboard' >
		<!-- Exit action -->
		<action name='exit' key='ESC' priority='0'
            target='basicInput' />
		<action name='exit' key='c' mask="ctrl" priority='0'
            target='basicInput' />
		
		<!-- Debug stuff -->
		<action name='console' key='F11' priority='0' target="chatapp" />
		<action name='debug' key='F9' priority='0' />
		<action name='stats' key='F10' priority='0' />
		<action name='screenshot' key='PrtSc' priority='0' target='basicinput' />
        <action name='gui' key='tab' priority='0' target='basicInput' />
		
		<!-- Camera 1 or Player 1 actions
				 For player 2, you can name them differently, or use the target name to differenciate players
		-->
		<action name='up' key='w' target='Cam' />
		<action name='down' key='s' target='Cam' />
		<action name='left' key='a' target='Cam' />
		<action name='right' key='d' target='Cam' />
		<action name='up' key='up' target='Cam' />
		<action name='down' key='down' target='Cam' />
		<action name='rotate_left' key='left' target='Cam' />
		<action name='rotate_right' key='right' target='Cam' />
		<action name='rotate_up' key='PgUp' target='Cam' />
		<action name='rotate_down' key='PgDown' target='Cam' />

	</input>
	
	<!-- Define actions for our Mouse -->
	<input device='mouse' target='Cam' >
		
		<action name='up' button='1' />
		<action name='down' button='2' />
		<action name='rotate_up' button='3' />
		<axis name='x' id='x' invert='false' />
		<axis name='y' id='y' invert='false' />
		<axis name='z' id='z' />
		
	</input>
	
	<!-- Define actions for the gamepad -->
	<input device='joy1' target='Me' >
		
		<action name='make_coffee' button='1' />
		<action name='select' button='9' />
		<action name='start' button='10' />
		<action name='push_left' button='11' />
		<action name='push_right' button='12' />
		
		<!-- Not sure yet how to handle the POV -->
		<action name='up' button='POV0_N' />
		<action name='down' button='POV0_S' />
		<action name='left' button='POV0_W' />
		<action name='right' button='POV0_E' />
		<action name='up_right' button='POV0_NE' />
		<action name='up_left' button='POV0_NW' />
		<action name='down_right' button='POV0_SE' />
		<action name='down_left' button='POV0_SW' />
		
		<axis name='x' id='1' />
		<axis name='y' id='2' invert='true' />
		<axis name='rx' id='3' />
		<axis name='ry' id='4' />
		
	</input>
	
		<!-- Define actions for the Joystick -->
	<input device='joy2' target='Me2' >
		
		<action name='make_coffee' button='1' />
		<action name='select' button='9' />
		<action name='start' button='10' />
		<action name='push_left' button='11' />
		<action name='push_right' button='12' />
		
		<!-- Not sure yet how to handle the POV -->
		<action name='up' button='POV0_N' />
		<action name='down' button='POV0_S' />
		<action name='left' button='POV0_W' />
		<action name='right' button='POV0_E' />
		<action name='up_right' button='POV0_NE' />
		<action name='up_left' button='POV0_NW' />
		<action name='down_right' button='POV0_SE' />
		<action name='down_left' button='POV0_SW' />
		
		<axis name='x' id='1' />
		<axis name='y' id='2' invert='true' />
		<axis name='rx' id='3' />
		<axis name='ry' id='4' />
		
	</input>

	
</sd7input>
